name: Demo the action
on: push
jobs:
  demo:
    name: Demo the repo's capability
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Upload a single file
        uses: devicons/public-upload-to-imgur@4e2ad8ec7db08624b9b3c20ddf2c3855e3ccef80
        id: step_1
        with:
          path: ./docs/example.PNG
          client_id: ${{secrets.IMGUR_CLIENT_ID}}
      - name: Upload a folder with multiple files
        uses: devicons/public-upload-to-imgur@4e2ad8ec7db08624b9b3c20ddf2c3855e3ccef80
        id: step_2
        with:
          path: ./docs/
          client_id: ${{secrets.IMGUR_CLIENT_ID}}
      - name: Upload a glob pattern
        uses: devicons/public-upload-to-imgur@4e2ad8ec7db08624b9b3c20ddf2c3855e3ccef80
        id: step_3
        with:
          path: ./*/*.png
          client_id: ${{secrets.IMGUR_CLIENT_ID}}
      - name: View results
        env:
          STEP_1_RESULT: ${{ fromJSON(steps.step_1.outputs.imgur_urls)[0] }}  # view only one result
          STEP_2_RESULT: ${{ steps.step_2.outputs.imgur_urls }}  
          STEP_3_RESULT: ${{ steps.step_3.outputs.markdown_urls }}  
        run: |
          echo $STEP_1_RESULT
          echo $STEP_2_RESULT
          echo $STEP_3_RESULT
